name: CI (smoke)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Serve and curl index
        run: |
          python3 -m http.server 8080 &
          sleep 2
          curl -sSf http://localhost:8080/index.html | grep -q "Social Hook + CTA Engine"